config/routes.rb
Rails.application.routes.draw do
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: 'homes#top'
    get '/users/quit' => 'users#quit'
    patch '/users/out' => 'users#out'
    get "search" => "searches#search"

    resources :users, only: [:show,:edit,:update, :create, :destroy, :quit, :out] do
      member do
        get :favorites
      end
    end
    resources :teams, only: [:show,:new,:edit,:create,:update] do
      resources :event_notices, only: [:new, :create]
      get "event_notices" => "event_notices#sent"
    end
    resources :diaries do
      resources :diary_comments, only: [:create,:destroy]
      resource :diary_favorites, only: [:create,:destroy]
    end
    resources :tactics, only: [:index, :show]
  end

  namespace :admin do
    get "search" => "searches#search"
    resources :users, only: [:index,:show,:edit,:update]
    resources :teams, only: [:index,:show,:edit,:update, :destroy]
    resources :diaries, only: [:index,:show,:edit,:update,:destroy] do
      resources :diary_comments, only: [:destroy]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/searches_controller.rb
class Admin::SearchesController < ApplicationController
  
  def search
    @word = params[:word]
    @range = params[:range]
    @search = params[:search]


    if @range == "Diary"
      @records = Diary.looks(@search, @word).order(created_at: :desc).page(params[:page]).per(8)
    elsif @range == "Tag"
      # タグが配列となっているため、ページネーションが使用できない
      @records = Tag.looks(@search, @word).sort_by(&:created_at).reverse
    end
  end
  
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/views/admin/searches/_form.html.erb
<%= form_with url: admin_search_path, method: :get, local: true do |f| %>
  <%= f.text_field :word %>
  <%= f.select :range, options_for_select([ ['Diary'], ['Tag']]) %>
  <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backword_match"], ["部分一致","partial_match"]]) %>
  <%= f.submit "検索" %>
<% end %>

app/views/admin/searches/search.html.erb
<div class="container px-5 px-sm-0">
  <h2 class="mb-4">Diaries search for <%= @word %></h2>
  <table class='table table-hover table-inverse'>
    <thead>
      <tr>
        <th></th>
        <th>投稿日</th>
        <th>投稿者</th>
        <th class="media-pc">タグ</th>
        <th>いいね</th>
        <th class="media-pc">コメント</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @records.each do |diary| %>
        <tr>
          <td>
            <%= link_to admin_diary_path(diary.id) do %>
              <%= image_tag diary.get_image(50,50) %>
            <% end %>
          </td>
          <td><%= diary.created_at.strftime('%Y/%m/%d') %></td>
          <td><%= diary.user.name %></td>
          <td class="media-pc">
            <% diary.tags.each do |tag| %>
              <li style="list-style: none;"><%= link_to tag.tag_name, admin_search_path(word: tag.tag_name, range:"Tag", search: "perfect_match") %></li>
            <% end %>
          </td>
          <td class=<%= "favorite-" + diary.id.to_s %>>
            <i class="fas fa-heart" aria-hidden="true" style="color: red;"></i>
            <%= diary.diary_favorites.count %>
          </td>
          <td class="media-pc"><%= render "admin/diary_comments/counter", diary: diary %></td>
          <td class="media-pc"><%= link_to "Edit", edit_diary_path(diary), class: "btn btn-sm btn-success edit_diary_#{diary.id}" %></td>
          <td class="media-pc"><%= link_to "Destroy", diary_path(diary), method: :delete, class: "btn btn-sm btn-danger destroy_diary_#{diary.id} ml-4", "data-confirm" => "本当に削除しますか？" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>