config/routes.rb
Rails.application.routes.draw do
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: 'homes#top'
    get '/users/quit' => 'users#quit'
    patch '/users/out' => 'users#out'
    get "search" => "searches#search"

    resources :users, only: [:show,:edit,:update, :create, :destroy, :quit, :out] do
      member do
        get :favorites
      end
    end
    resources :teams, only: [:show,:new,:edit,:create,:update] do
      resources :event_notices, only: [:new, :create]
      get "event_notices" => "event_notices#sent"
    end
    resources :diaries do
      resources :diary_comments, only: [:create,:destroy]
      resource :diary_favorites, only: [:create,:destroy]
    end
    resources :tactics, only: [:index, :show]
  end

  namespace :admin do
    get "search" => "searches#search"
    resources :users, only: [:index,:show,:edit,:update]
    resources :teams, only: [:index,:show,:edit,:update, :destroy]
    resources :diaries, only: [:index,:show,:edit,:update,:destroy] do
      resources :diary_comments, only: [:destroy]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/diary.rb
class Diary < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :diary_comments, dependent: :destroy
  has_many :diary_favorites, dependent: :destroy
  has_many :tactic_tags, dependent: :destroy
  has_many :tags, through: :tactic_tags

  validates :place, presence: true
  validates :result, presence: true
  validates :good, presence: true, length: {maximum: 200}
  validates :bad, presence: true, length: {maximum: 200}

  def save_tags(savediary_tags)
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags = current_tags - savediary_tags
    new_tags = savediary_tags - current_tags

    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(tag_name:old_name)
    end

    new_tags.each do |new_name|
      diary_tag = Tag.find_or_create_by(tag_name:new_name)
      self.tags << diary_tag
    end
  end

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_img.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'img/jpeg')
    end
    image.variant(resize_to_fit: [width, height]).processed
  end

  def favorited_by?(user)
    diary_favorites.exists?(user_id: user.id)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @diary = Diary.where("bad LIKE?","#{word}").or(Diary.where("good LIKE?","#{word}"))
    elsif search == "forward_match"
      @diary = Diary.where("bad LIKE?","#{word}%").or(Diary.where("good LIKE?","#{word}%"))
    elsif search == "backward_match"
      @diary = Diary.where("bad LIKE?","%#{word}").or(Diary.where("good LIKE?","%#{word}"))
    elsif search == "partial_match"
      @diary = Diary.where("bad LIKE?","%#{word}%").or(Diary.where("good LIKE?","%#{word}%"))
    else
      @diary = Diary.all
    end
  end
end

app/controllers/admin/diaries_controller.rb
class Admin::DiariesController < ApplicationController
  def index
    @diaries = Diary.all.order(created_at: :desc).page(params[:page]).per(8)
  end

  def show
    @diary = Diary.find(params[:id])
  end

  def edit
    @diary = Diary.find(params[:id])
    @tags = Tag.all
  end

  def update
    @diary = Diary.find(params[:id])
    if @diary.update(diary_params)
      flash[:notice] = 'You have updated diary successfully.'
      redirect_to admin_diary_path(@diary)
    else
      render :edit
    end
  end

  def destroy
    @diary = Diary.find(params[:id])
    Diary.find(params[:id]).destroy
    redirect_to admin_diaries_path
  end

  private

  def diary_params
    params.require(:diary).permit(:image, :place, :result, :good, :bad, {:tag_ids => []})
  end

end

app/helpers/admin/diaries_helper.rb
module Admin::DiariesHelper
end

app/views/admin/diaries/_form.html.erb
<%= form_with model: [:admin, diary],local:true do |f| %>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, accept: "image/*" %>
  </div>
  <div class="form-group">
    <%= f.label :place %>
    <%= f.text_field :place, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :result %>
    <%= f.select :result, [['WIN','WIN'], ['LOSE','LOSE'], ['DRAW','DRAW']] %>
  </div>

  <div class="form-group">
    <%= f.label :good %>
    <%= f.text_area :good, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :bad %>
    <%= f.text_area :bad, class: 'form-control' %>
  </div>

  <div class="form-group">
      <%# 推奨タグ3個を表示 %>
      <div class="check-box">
        <%= collection_check_boxes(:diary, :tag_ids, tags.limit(9), :id, :tag_name) do |b| %>
        <%= b.label { b.check_box + b.text } %>
        <% end %>
      </div>
    <%= f.text_field :tag_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit 'Update diary', class: 'btn btn-info' %>
  </div>
<% end %>

app/views/admin/diaries/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>投稿日</th>
      <th>投稿者</th>
      <th class="media-pc">タグ</th>
      <th>いいね</th>
      <th class="media-pc">コメント</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% diaries.each do |diary| %>
      <tr>
        <td>
          <%= link_to admin_diary_path(diary.id) do %>
            <%= image_tag diary.get_image(50,50) %>
          <% end %>
        </td>
        <td><%= diary.created_at.strftime('%Y/%m/%d') %></td>
        <td><%= diary.user.name %></td>
        <td class="media-pc">
          <% diary.tags.each do |tag| %>
            <li style="list-style: none;"><%= link_to tag.tag_name, admin_search_path(word: tag.tag_name, range:"Tag", search: "perfect_match") %></li>
          <% end %>
        </td>
        <td class=<%= "favorite-" + diary.id.to_s %>>
          <i class="fas fa-heart" aria-hidden="true" style="color: red;"></i>
          <%= diary.diary_favorites.count %>
        </td>
        <td class="media-pc"><%= render "admin/diary_comments/counter", diary: diary %></td>
        <td class="media-pc"><%= link_to "Edit", edit_diary_path(diary), class: "btn btn-sm btn-success edit_diary_#{diary.id}" %></td>
        <td class="media-pc"><%= link_to "Destroy", diary_path(diary), method: :delete, class: "btn btn-sm btn-danger destroy_diary_#{diary.id} ml-4", "data-confirm" => "本当に削除しますか？" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate diaries %>

app/views/admin/diaries/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Editing Diary</h2>
      <%= render 'layouts/errors', obj: @diary %>
      <%= render 'form', diary: @diary, tags: @tags %>
      <span>
        <%= link_to "Show", admin_diary_path(@diary), class: "diary_#{@diary.id}" %>
      </span>
      |
      <span>
        <%= link_to "Index", admin_diaries_path, class: "back" %>
      </span>
    </div>
  </div>
</div>

app/views/admin/diaries/index.html.erb
<div class="container px-5 px-sm-0">
  <h2 class="mb-4">Diaries</h2>
    <%= render 'admin/searches/form' %>
    <%= render 'index', diaries: @diaries %>
</div>

app/views/admin/diaries/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-lg-4">
    <h2 class="mb-5">Diary detail</h2>
      <%= image_tag @diary.get_image(400,400) %>
    </div>
    <div class= "col-lg-4 offset-lg-1" style="margin-top:90px;">
      <p>投稿日：<%= @diary.created_at.strftime('%Y/%m/%d') %></p>
      <p>場所：<%= @diary.place %></p>
      <p>結果：<%= @diary.result %></p>
      <p>良かった点：<%= @diary.good %></p>
      <p>悪かった点：<%= @diary.bad %></p>
      <li style="list-style: none;">タグ : 
        <% @diary.tags.each do |tag| %>
          <%= link_to tag.tag_name, admin_search_path(word: tag.tag_name, range:"Tag", search: "perfect_match") %>
        <% end %>
      </li>
      <%= link_to "Edit", edit_admin_diary_path(@diary), class: "btn btn-sm btn-success edit_diary_#{@diary.id} mt-4" %>
      <%= link_to "Destroy", admin_diary_path(@diary), method: :delete, class: "btn btn-sm btn-danger destroy_diary_#{@diary.id} mt-4 ml-4" %>
    </div>
    <div class="col-lg-3" style="margin-top:90px;">
      <div class=<%= "favorite-" + @diary.id.to_s %>>
        <i class="fas fa-heart" aria-hidden="true" style="color: red;"></i>
        <%= @diary.diary_favorites.count %>
      </div>
      <div class="diary-comments-counter">
        <%= render "admin/diary_comments/counter", diary: @diary %>
      </div>
      <div class="diary-comments-index">
        <%= render "admin/diary_comments/index", diary: @diary %>
      </div>
    </div>
  </div>
</div>