config/routes.rb
Rails.application.routes.draw do
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: 'homes#top'
    get '/users/quit' => 'users#quit'
    patch '/users/out' => 'users#out'
    get "search" => "searches#search"

    resources :users, only: [:show,:edit,:update, :create, :destroy, :quit, :out] do
      member do
        get :favorites
      end
    end
    resources :teams, only: [:show,:new,:edit,:create,:update] do
      resources :event_notices, only: [:new, :create]
      get "event_notices" => "event_notices#sent"
    end
    resources :diaries do
      resources :diary_comments, only: [:create,:destroy]
      resource :diary_favorites, only: [:create,:destroy]
    end
    resources :tactics, only: [:index, :show]
  end

  namespace :admin do
    get "search" => "searches#search"
    resources :users, only: [:index,:show,:edit,:update]
    resources :teams, only: [:index,:show,:edit,:update, :destroy]
    resources :diaries, only: [:index,:show,:edit,:update,:destroy] do
      resources :diary_comments, only: [:destroy]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :diaries, dependent: :destroy
  has_many :diary_comments, dependent: :destroy
  has_many :diary_favorites, dependent: :destroy
  belongs_to :team

  validates :team_id, presence: true
  validates :name, presence: true
  validates :age, presence: true
  validates :number, presence: true
  validates :position, presence: true
  validates :speed_rate, presence: true
  validates :power_rate, presence: true
  validates :tactics_rate, presence: true

  enum is_deleted: {"有効": false,"退会": true }

  def create_user_icon
    [icon_00.png, icon_00.png, icon_01.png, icon_02.png, icon_03.png, icon_04.png, icon_05.png].sample
  end

  def get_profile_image
    sample_image = ['icon_00.png', 'icon_01.png', 'icon_02.png', 'icon_03.png', 'icon_04.png', 'icon_05.png'].sample
    file_path = Rails.root.join("app/assets/images/#{sample_image}")
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpeg', content_type: 'image/jpeg')
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @diaries = @user.diaries.order(created_at: :desc).page(params[:page]).per(8)
  end

  def edit
     @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user)
    else
      render :edit
    end
  end

  def quit
    @user = current_user
  end

  def out
    @user = current_user
    @user.update(is_deleted: "退会")
    reset_session
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:team_id, :name, :age, :number, :position, :speed_rate, :power_rate, :tactics_rate, :is_deleted)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th>status</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td>
          <%= link_to admin_user_path(user) do %>
            <%= image_tag user.profile_image.variant(resize_to_limit: [50, 50]) %>
          <% end %>
        </td>
        <td><%= user.name %></td>
        <% if user.is_deleted == "有効" %>
          <td class="text-primary font-weight-bold"><%= user.is_deleted %></td>
        <% else %>
          <td class="text-black-50 font-weight-bold"><%= user.is_deleted %></td>
        <% end %>
        <td><%= link_to 'Edit', edit_admin_user_path(user), class: "admin_user_#{user.id} btn btn-sm btn-success" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/users/_info.html.erb
<table class="table">
  <tr>
    <th>icon</th>
    <th><%= image_tag user.profile_image.variant(resize_to_limit: [50, 50]) %></th>
  </tr>
  <tr>
    <th>team</th>
    <th><%= user.team.team_name %></th>
  </tr>
  <tr>
    <th>name</th>
    <th><%= user.name %></th>
  </tr>
  <tr>
    <th>age</th>
    <th><%= user.age %></th>
  </tr>
  <tr>
    <th>number</th>
    <th><%= user.number %></th>
  </tr>
  <tr>
    <th>position</th>
    <th><%= user.position %></th>
  </tr>
  <tr>
    <th>speed_rate</th>
    <th><div id="speed_rate_<%= user.id %>" class="form-group"></div></th>
  </tr>
  <tr>
    <th>power_rate</th>
    <th><div id="power_rate_<%= user.id %>" class="form-group"></div></th>
  </tr>
  <tr>
    <th>tactics_rate</th>
    <th><div id="tactics_rate_<%= user.id %>" class="form-group"></div></th>
  </tr>
</table>
<p><%= link_to "プロフィール編集",edit_admin_user_path(user) %></p>


<script>
$(document).on('turbolinks:load', function() {
  $('#speed_rate_<%= user.id %>').empty();
  $('#speed_rate_<%= user.id %>').raty({
    size: 20,
    starOff:  '<%= asset_path("star-off.png") %>',
    starOn : '<%= asset_path("star-on.png") %>',
    starHalf: '<%= asset_path("star-half.png") %>',
    half: true,
    readOnly: true,
    score: <%= user.speed_rate %>,
  });
  $('#power_rate_<%= user.id %>').empty();
  $('#power_rate_<%= user.id %>').raty({
    size: 20,
    starOff:  '<%= asset_path("star-off.png") %>',
    starOn : '<%= asset_path("star-on.png") %>',
    starHalf: '<%= asset_path("star-half.png") %>',
    half: true,
    readOnly: true,
    score: <%= user.power_rate %>,
  });
  $('#tactics_rate_<%= user.id %>').empty();
  $('#tactics_rate_<%= user.id %>').raty({
    size: 20,
    starOff:  '<%= asset_path("star-off.png") %>',
    starOn : '<%= asset_path("star-on.png") %>',
    starHalf: '<%= asset_path("star-half.png") %>',
    half: true,
    readOnly: true,
    score: <%= user.tactics_rate %>,
  });
});
</script>

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>プロフィール編集</h2>
      <%= form_with model: [:admin, @user], local:true do |f| %>
        <%= render 'layouts/errors', obj: @user %>
        <div class="field">
          <%= f.label :team_id %><br>
          <%= f.select :team_id, options_from_collection_for_select(Team.all, :id, :team_name, @user.team_id) %>
        </div>

        <div class="field">
          <%= f.label :name %><br>
          <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
        </div>

        <div class="field">
          <%= f.label :age %><br>
          <%= f.number_field :age %>
        </div>

        <div class="field">
          <%= f.label :number %><br>
          <%= f.number_field :number %>
        </div>

        <div class="field">
          <%= f.label :position %><br>
          <%= f.select :position, [['ピヴォ','ピヴォ'], ['アラ','アラ'], ['フィクソ','フィクソ'], ['ゴレイロ','ゴレイロ']] %>
        </div>

        <%= f.label :speed_rate %>
        <div class="form-group" id="speed_rate_<%= @user.id %>">
        </div>
        <%= f.label :power_rate %>
        <div class="form-group" id="power_rate_<%= @user.id %>">
        </div>
        <%= f.label :tactics_rate %>
        <div class="form-group" id="tactics_rate_<%= @user.id %>">
        </div>

        <script>
        $(document).on('turbolinks:load', function() {
          $('#speed_rate_<%= @user.id %>').empty();
          $('#speed_rate_<%= @user.id %>').raty({
            size: 20,
            starOff:  '<%= asset_path("star-off.png") %>',
            starOn : '<%= asset_path("star-on.png") %>',
            starHalf: '<%= asset_path("star-half.png") %>',
            half: true,
            readOnly: false,
            scoreName: 'user[speed_rate]',
            score: <%= @user.speed_rate %>,
          });
          $('#power_rate_<%= @user.id %>').empty();
          $('#power_rate_<%= @user.id %>').raty({
            size: 20,
            starOff:  '<%= asset_path("star-off.png") %>',
            starOn : '<%= asset_path("star-on.png") %>',
            starHalf: '<%= asset_path("star-half.png") %>',
            half: true,
            readOnly: false,
            scoreName: 'user[power_rate]',
            score: <%= @user.power_rate %>,
          });
          $('#tactics_rate_<%= @user.id %>').empty();
          $('#tactics_rate_<%= @user.id %>').raty({
            size: 20,
            starOff:  '<%= asset_path("star-off.png") %>',
            starOn : '<%= asset_path("star-on.png") %>',
            starHalf: '<%= asset_path("star-half.png") %>',
            half: true,
            readOnly: false,
            scoreName: 'user[tactics_rate]',
            score: <%= @user.tactics_rate %>,
          });
        });
        </script>

        <div>
          <%= f.radio_button :is_deleted, "有効" %>
          <%= f.label :is_deleted, "有効", class: "m-0" %>
          <%= f.radio_button :is_deleted, "退会" %>
          <%= f.label :is_deleted, "退会", class: "m-0" %>
        </div>

        <div class="form-group">
          <%= f.submit class:"btn btn-info" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <h2>Users</h2>
    <%= render 'admin/users/index',users: @users %>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-4">
      <h2>User info</h2>
      <%= render 'info', user: @user %>
    </div>
    <div class="col-md-7 offset-md-1">
      <h2>Diaries</h2>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>投稿日</th>
            <th>投稿者</th>
            <th class="media-pc">タグ</th>
            <th>いいね</th>
            <th class="media-pc">コメント</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @diaries.each do |diary| %>
            <tr>
              <td>
                <%= link_to admin_diary_path(diary.id) do %>
                  <%= image_tag diary.get_image(50,50) %>
                <% end %>
              </td>
              <td><%= diary.created_at.strftime('%Y/%m/%d') %></td>
              <td><%= diary.user.name %></td>
              <td class="media-pc">
                <% diary.tags.each do |tag| %>
                  <li style="list-style: none;"><%= link_to tag.tag_name, admin_search_path(word: tag.tag_name, range:"Tag", search: "perfect_match") %></li>
                <% end %>
              </td>
              <td class=<%= "favorite-" + diary.id.to_s %>>
                <i class="fas fa-heart" aria-hidden="true" style="color: red;"></i>
                <%= diary.diary_favorites.count %>
              </td>
              <td class="media-pc"><%= render "admin/diary_comments/counter", diary: diary %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @diaries %>
    </div>
  </div>
</div>