config/routes.rb
Rails.application.routes.draw do
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: 'homes#top'
    get '/users/quit' => 'users#quit'
    patch '/users/out' => 'users#out'
    get "search" => "searches#search"

    resources :users, only: [:show,:edit,:update, :create, :destroy, :quit, :out] do
      member do
        get :favorites
      end
    end
    resources :teams, only: [:show,:new,:edit,:create,:update] do
      resources :event_notices, only: [:new, :create]
      get "event_notices" => "event_notices#sent"
    end
    resources :diaries do
      resources :diary_comments, only: [:create,:destroy]
      resource :diary_favorites, only: [:create,:destroy]
    end
    resources :tactics, only: [:index, :show]
  end

  namespace :admin do
    get "search" => "searches#search"
    resources :users, only: [:index,:show,:edit,:update]
    resources :teams, only: [:index,:show,:edit,:update, :destroy]
    resources :diaries, only: [:index,:show,:edit,:update,:destroy] do
      resources :diary_comments, only: [:destroy]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_ad_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class='container'>
    <%= link_to 'futsal_diary', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                      aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
        <li>
          <%= link_to admin_teams_path, class: 'nav-link text-light' do %>
            <h3>Teams</h3>
          <% end %>
        </li>
          <li>
          <%= link_to admin_users_path, class: 'nav-link text-light' do %>
            <h3>Users</h3>
          <% end %>
        </li>
        <li>
          <%= link_to admin_diaries_path, class: 'nav-link text-light' do %>
            <h3>diaries</h3>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-light' do %>
            <h3>Log out</h3>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= obj.errors.count %> errors prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class='container'>
    <%= link_to 'futsal_diary', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                      aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
        <li>
          <%= link_to root_path, class: 'nav-link text-light' do %>
            <i class="fas fa-futbol"></i> futsal_diaryについて
          <% end %>
        </li>
        <li>
          <%= link_to new_team_path, class: 'nav-link text-light' do %>
            <i class="fas fa-users"></i> チーム登録
          <% end %>
        </li>
        <li>
          <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
            <i class="fas fa-user"></i> ユーザー登録
          <% end %>
        </li>
        <li>
          <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
            <i class="fas fa-sign-in-alt"></i> ユーザーログイン
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_pub_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class='container'>
    <%= link_to 'futsal_diary', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                      aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
        <li>
          <%= link_to team_path(current_user.team), class: 'nav-link text-light' do %>
            <h3>Team</h3>
          <% end %>
        </li>
          <li>
          <%= link_to user_path(current_user), class: 'nav-link text-light' do %>
            <h3>My page</h3>
          <% end %>
        </li>
        <li>
          <%= link_to diaries_path, class: 'nav-link text-light' do %>
            <h3>diaries</h3>
          <% end %>
        </li>
        <li>
          <%= link_to tactics_path, class: 'nav-link text-light' do %>
            <h3>Tactics</h3>
          <% end %>
        </li>
            <li>
          <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
            <h3>log out</h3>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FutsalDiary</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if user_signed_in? %>
        <%= render 'layouts/pub_header' %>
      <% elsif admin_signed_in? %>
        <%= render 'layouts/ad_header' %>
      <% else %>
        <%= render 'layouts/header' %>
      <% end %>
    </header>
    <main>
      <p class="notice"><%= notice %></p>
      <%= yield %>
    </main>
    <footer>
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>